[package]
name = "b2m"
version = "1.0.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gmod = "17.0.0"
lazy_static = "1.4.0"
reqwest = {version = "0.11.24", features = ["blocking"]}
serde_json = "1.0.113"
crc32fast = "1.4.0"
